baseurl: /beatmix
# markdown: KramdownCustom
markdown: kramdown
permalink: /:categories/:title.html
collections: 
    projects:
        output: false
gems:
# - kramdown
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
